@echo off
echo Starting GenAI Career Copilot Frontend...
cd Carrier-Copilot-new\frontend
if not exist node_modules (
    echo Installing dependencies...
    call npm install
)
echo Starting Vite development server...
npm run dev
