import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { toast } from 'react-toastify';

const Roadmap = ({ darkMode, userEmail }) => {
  const [targetRole, setTargetRole] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);

  useEffect(() => {
    // Load previous result from localStorage
    const savedResult = localStorage.getItem('roadmapData');
    if (savedResult) {
      try {
        setResult(JSON.parse(savedResult));
      } catch (e) {
        console.error('Failed to parse saved result');
      }
    }
  }, []);

  const handleGenerate = async () => {
    const email = userEmail || localStorage.getItem('userEmail');
    
    if (!email) {
      toast.error('Please upload your resume first in the Resume Analyzer tab');
      return;
    }
    
    if (!targetRole.trim()) {
      toast.error('Please enter a target role');
      return;
    }

    setLoading(true);
    try {
      const response = await axios.post('http://localhost:8000/api/analyze-role', {
        email: email,
        role: targetRole
      });
      
      setResult(response.data);
      
      // Save result to localStorage
      localStorage.setItem('roadmapData', JSON.stringify(response.data));
      
      toast.success('🗺️ Personalized roadmap generated by AI!');
    } catch (error) {
      if (error.response?.status === 404) {
        toast.error('No resume found. Please upload your resume first!');
      } else {
        toast.error('Failed to generate roadmap. Make sure the backend is running.');
      }
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  const levelColors = {
    beginner: { bg: 'from-green-500 to-emerald-500', border: 'border-green-500', text: 'text-green-600' },
    intermediate: { bg: 'from-blue-500 to-cyan-500', border: 'border-blue-500', text: 'text-blue-600' },
    advanced: { bg: 'from-purple-500 to-pink-500', border: 'border-purple-500', text: 'text-purple-600' }
  };

  return (
    <div className="max-w-5xl">
      <div className="mb-6">
        <h2 className={`text-3xl font-bold mb-2 ${darkMode ? 'text-white' : 'text-gray-900'}`}>
          🗺️ Personalized Learning Roadmap
        </h2>
        <p className={`text-sm ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>
          Step 3: Get an AI-generated learning path tailored to your skills
        </p>
      </div>

      <div className={`p-6 rounded-xl ${darkMode ? 'bg-gray-800' : 'bg-white'} shadow-lg mb-6`}>
        {userEmail && (
          <div className={`mb-4 p-3 rounded-lg ${darkMode ? 'bg-blue-900/20' : 'bg-blue-50'}`}>
            <p className={`text-sm ${darkMode ? 'text-blue-300' : 'text-blue-700'}`}>
              📧 Generating roadmap for: <strong>{userEmail}</strong>
            </p>
          </div>
        )}

        <div className="mb-4">
          <label className={`block mb-2 font-medium ${darkMode ? 'text-gray-300' : 'text-gray-700'}`}>
            Target Role <span className="text-red-500">*</span>
          </label>
          <input
            type="text"
            value={targetRole}
            onChange={(e) => setTargetRole(e.target.value)}
            placeholder="e.g., Frontend Developer, Data Scientist, Backend Engineer"
            className={`w-full px-4 py-3 rounded-lg border ${
              darkMode 
                ? 'bg-gray-700 border-gray-600 text-white placeholder-gray-400' 
                : 'bg-white border-gray-300 text-gray-900'
            } focus:ring-2 focus:ring-primary focus:border-transparent`}
          />
        </div>

        <button
          onClick={handleGenerate}
          disabled={loading}
          className="w-full bg-gradient-to-r from-primary to-secondary text-white py-3 rounded-lg font-semibold hover:shadow-lg transform hover:scale-105 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center space-x-2"
        >
          {loading ? (
            <>
              <svg className="animate-spin h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
              <span>AI is creating your roadmap...</span>
            </>
          ) : (
            <>
              <span>🤖</span>
              <span>Generate Personalized Roadmap</span>
            </>
          )}
        </button>
      </div>

      {result && (
        <div>
          {/* Check if roadmap exists and has data */}
          {!result.roadmap || Object.keys(result.roadmap).length === 0 || 
           (!result.roadmap.beginner?.length && !result.roadmap.intermediate?.length && !result.roadmap.advanced?.length) ? (
            <div className={`p-6 rounded-xl ${darkMode ? 'bg-yellow-900/20 border border-yellow-500' : 'bg-yellow-50 border border-yellow-200'} shadow-lg`}>
              <p className={`${darkMode ? 'text-yellow-300' : 'text-yellow-800'} mb-3`}>
                ⚠️ Roadmap generation failed. This usually means:
              </p>
              <ul className={`list-disc list-inside space-y-1 ${darkMode ? 'text-yellow-300' : 'text-yellow-800'}`}>
                <li>Gemini API is not properly configured</li>
                <li>Backend needs to be restarted after upgrading Gemini</li>
                <li>API key might be invalid</li>
              </ul>
              <p className={`mt-3 text-sm ${darkMode ? 'text-yellow-400' : 'text-yellow-700'}`}>
                💡 Run <code className="bg-black/20 px-2 py-1 rounded">upgrade-gemini.bat</code> then restart the backend
              </p>
            </div>
          ) : (
            <>
          {/* Header Card with Role Intelligence */}
          <div className={`p-6 rounded-xl ${darkMode ? 'bg-gradient-to-r from-purple-900/30 to-pink-900/30 border border-purple-500' : 'bg-gradient-to-r from-purple-50 to-pink-50 border border-purple-200'} shadow-lg mb-6`}>
            <h3 className={`text-2xl font-bold mb-3 ${darkMode ? 'text-white' : 'text-gray-900'}`}>
              🎯 Your Personalized Path to {result.target_role}
            </h3>
            
            {/* Role Intelligence Grid */}
            {result.skill_gap?.role_intelligence && (
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-4">
                <div className={`p-3 rounded-lg ${darkMode ? 'bg-gray-800/50' : 'bg-white/50'}`}>
                  <p className={`text-xs ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>💰 Salary Range</p>
                  <p className={`text-lg font-bold ${darkMode ? 'text-green-400' : 'text-green-600'}`}>
                    ₹{result.skill_gap.role_intelligence.salary_range_lpa} LPA
                  </p>
                </div>
                <div className={`p-3 rounded-lg ${darkMode ? 'bg-gray-800/50' : 'bg-white/50'}`}>
                  <p className={`text-xs ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>📈 Market Demand</p>
                  <p className={`text-lg font-bold ${result.skill_gap.role_intelligence.market_demand === 'High' ? 'text-blue-500' : 'text-yellow-500'}`}>
                    {result.skill_gap.role_intelligence.market_demand}
                  </p>
                </div>
                <div className={`p-3 rounded-lg ${darkMode ? 'bg-gray-800/50' : 'bg-white/50'}`}>
                  <p className={`text-xs ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>⏱️ Time to Learn</p>
                  <p className={`text-lg font-bold ${darkMode ? 'text-purple-400' : 'text-purple-600'}`}>
                    {result.skill_gap.role_intelligence.time_to_learn}
                  </p>
                </div>
                <div className={`p-3 rounded-lg ${darkMode ? 'bg-gray-800/50' : 'bg-white/50'}`}>
                  <p className={`text-xs ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>🚀 Growth</p>
                  <p className={`text-lg font-bold ${darkMode ? 'text-orange-400' : 'text-orange-600'}`}>
                    {result.skill_gap.role_intelligence.growth_potential}
                  </p>
                </div>
              </div>
            )}

            <p className={`${darkMode ? 'text-gray-300' : 'text-gray-700'} mb-2`}>
              ⏱️ Estimated Time: <strong>{result.ai_insights?.estimated_time || '3-6 months'}</strong>
            </p>
            
            {result.skill_gap?.role_intelligence?.top_companies && (
              <p className={`text-sm ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>
                🏢 Top Hiring Companies: <strong>{result.skill_gap.role_intelligence.top_companies.slice(0, 3).join(', ')}</strong>
              </p>
            )}
            
            <p className={`text-sm mt-2 ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>
              💡 This roadmap is personalized based on your current skills and focuses on what you need to learn.
            </p>
          </div>

          {/* Skill Gap Summary */}
          {result.skill_gap && (
            <div className={`p-4 rounded-lg mb-6 ${darkMode ? 'bg-gray-800' : 'bg-white'} shadow`}>
              <div className="flex items-center justify-between">
                <div>
                  <p className={`text-sm ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>Your Progress</p>
                  <p className={`text-2xl font-bold ${darkMode ? 'text-white' : 'text-gray-900'}`}>
                    {result.skill_gap.completion_percentage}% Complete
                  </p>
                </div>
                <div className="text-right">
                  <p className={`text-sm ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>Skills to Learn</p>
                  <p className={`text-2xl font-bold ${darkMode ? 'text-orange-400' : 'text-orange-600'}`}>
                    {result.skill_gap.missing_skills?.length || 0}
                  </p>
                </div>
              </div>
            </div>
          )}

          {/* Roadmap Timeline */}
          <div className="space-y-8">
            {['beginner', 'intermediate', 'advanced'].map((level, levelIndex) => (
              result.roadmap && result.roadmap[level] && Array.isArray(result.roadmap[level]) && result.roadmap[level].length > 0 && (
                <div key={level}>
                  <div className="flex items-center mb-4">
                    <div className={`bg-gradient-to-r ${levelColors[level].bg} text-white px-6 py-2 rounded-full font-bold text-lg capitalize shadow-lg`}>
                      {level === 'beginner' ? '🌱' : level === 'intermediate' ? '🚀' : '⭐'} {level}
                    </div>
                  </div>

                  <div className="space-y-4 ml-8 relative">
                    {/* Vertical line */}
                    {levelIndex < 2 && (
                      <div className={`absolute left-0 top-0 bottom-0 w-1 ${darkMode ? 'bg-gray-700' : 'bg-gray-200'}`} style={{ left: '-1rem' }}></div>
                    )}

                    {result.roadmap[level].map((item, index) => (
                      <div
                        key={index}
                        className={`p-5 rounded-xl ${darkMode ? 'bg-gray-800' : 'bg-white'} shadow-lg hover:shadow-xl transition-all border-l-4 ${levelColors[level].border} relative`}
                      >
                        {/* Dot on timeline */}
                        <div className={`absolute -left-10 top-6 w-4 h-4 rounded-full ${levelColors[level].bg} border-4 ${darkMode ? 'border-gray-900' : 'border-white'}`}></div>

                        <div className="flex justify-between items-start mb-2">
                          <h4 className={`text-xl font-bold ${darkMode ? 'text-white' : 'text-gray-900'}`}>
                            {item.title}
                          </h4>
                          <span className={`px-3 py-1 rounded-full text-sm font-medium ${
                            darkMode ? 'bg-gray-700 text-gray-300' : 'bg-gray-100 text-gray-700'
                          }`}>
                            ⏱️ {item.duration}
                          </span>
                        </div>
                        
                        <p className={`mb-3 ${darkMode ? 'text-gray-300' : 'text-gray-600'}`}>
                          {item.description}
                        </p>
                        
                        {item.why && (
                          <p className={`text-sm italic mb-3 ${darkMode ? 'text-gray-400' : 'text-gray-500'}`}>
                            💡 Why: {item.why}
                          </p>
                        )}

                        {/* Intelligence Data */}
                        {item.intelligence && (
                          <div className={`mb-3 p-3 rounded-lg ${darkMode ? 'bg-gray-700/50' : 'bg-gray-50'}`}>
                            <div className="grid grid-cols-2 gap-2 text-sm">
                              <div>
                                <span className={darkMode ? 'text-gray-400' : 'text-gray-600'}>📊 Demand: </span>
                                <span className={`font-semibold ${item.intelligence.demand === 'Very High' ? 'text-green-500' : item.intelligence.demand === 'High' ? 'text-blue-500' : 'text-yellow-500'}`}>
                                  {item.intelligence.demand}
                                </span>
                              </div>
                              <div>
                                <span className={darkMode ? 'text-gray-400' : 'text-gray-600'}>🎯 Difficulty: </span>
                                <span className={`font-semibold ${darkMode ? 'text-gray-300' : 'text-gray-700'}`}>
                                  {item.intelligence.difficulty}
                                </span>
                              </div>
                              <div>
                                <span className={darkMode ? 'text-gray-400' : 'text-gray-600'}>⏰ Time: </span>
                                <span className={`font-semibold ${darkMode ? 'text-gray-300' : 'text-gray-700'}`}>
                                  {item.intelligence.learning_time}
                                </span>
                              </div>
                              <div>
                                <span className={darkMode ? 'text-gray-400' : 'text-gray-600'}>💰 Impact: </span>
                                <span className={`font-semibold ${item.intelligence.salary_impact === 'High' ? 'text-green-500' : 'text-blue-500'}`}>
                                  {item.intelligence.salary_impact}
                                </span>
                              </div>
                            </div>
                          </div>
                        )}

                        {/* Resources Section */}
                        {item.resources && (
                          <div className={`mt-4 p-4 rounded-lg ${darkMode ? 'bg-gray-700/30' : 'bg-blue-50'}`}>
                            <h5 className={`font-semibold mb-3 ${darkMode ? 'text-blue-300' : 'text-blue-700'}`}>
                              📚 Learning Resources
                            </h5>
                            
                            {/* Documentation */}
                            {item.resources.documentation && (
                              <div className="mb-3">
                                <p className={`text-sm font-medium mb-1 ${darkMode ? 'text-gray-300' : 'text-gray-700'}`}>
                                  📖 Documentation:
                                </p>
                                <a 
                                  href={item.resources.documentation.url} 
                                  target="_blank" 
                                  rel="noopener noreferrer"
                                  className={`text-sm ${darkMode ? 'text-blue-400 hover:text-blue-300' : 'text-blue-600 hover:text-blue-800'} underline`}
                                >
                                  {item.resources.documentation.title}
                                </a>
                              </div>
                            )}

                            {/* YouTube Courses */}
                            {item.resources.youtube_courses && item.resources.youtube_courses.length > 0 && (
                              <div className="mb-3">
                                <p className={`text-sm font-medium mb-1 ${darkMode ? 'text-gray-300' : 'text-gray-700'}`}>
                                  🎥 Video Courses:
                                </p>
                                <ul className="space-y-1">
                                  {item.resources.youtube_courses.map((course, idx) => (
                                    <li key={idx}>
                                      <a 
                                        href={course.search_url} 
                                        target="_blank" 
                                        rel="noopener noreferrer"
                                        className={`text-sm ${darkMode ? 'text-blue-400 hover:text-blue-300' : 'text-blue-600 hover:text-blue-800'} underline`}
                                      >
                                        {course.title}
                                      </a>
                                    </li>
                                  ))}
                                </ul>
                              </div>
                            )}

                            {/* Projects */}
                            {item.resources.practice_projects && item.resources.practice_projects.length > 0 && (
                              <div className="mb-3">
                                <p className={`text-sm font-medium mb-1 ${darkMode ? 'text-gray-300' : 'text-gray-700'}`}>
                                  💻 Practice Projects:
                                </p>
                                <ul className="space-y-1">
                                  {item.resources.practice_projects.map((project, idx) => (
                                    <li key={idx} className={`text-sm ${darkMode ? 'text-gray-300' : 'text-gray-700'}`}>
                                      • {project.title}
                                    </li>
                                  ))}
                                </ul>
                              </div>
                            )}

                            {/* Practice Platforms */}
                            {item.resources.practice_platforms && item.resources.practice_platforms.length > 0 && (
                              <div>
                                <p className={`text-sm font-medium mb-1 ${darkMode ? 'text-gray-300' : 'text-gray-700'}`}>
                                  🏆 Practice On:
                                </p>
                                <div className="flex flex-wrap gap-2">
                                  {item.resources.practice_platforms.map((platform, idx) => (
                                    <a 
                                      key={idx}
                                      href={platform.url} 
                                      target="_blank" 
                                      rel="noopener noreferrer"
                                      className={`text-xs px-2 py-1 rounded ${darkMode ? 'bg-gray-600 text-gray-200 hover:bg-gray-500' : 'bg-gray-200 text-gray-700 hover:bg-gray-300'}`}
                                    >
                                      {platform.name}
                                    </a>
                                  ))}
                                </div>
                              </div>
                            )}
                          </div>
                        )}

                        {/* Key Concepts */}
                        {item.key_concepts && item.key_concepts.length > 0 && (
                          <div className="mt-3">
                            <p className={`text-sm font-medium mb-2 ${darkMode ? 'text-gray-300' : 'text-gray-700'}`}>
                              🎯 Key Concepts to Master:
                            </p>
                            <div className="flex flex-wrap gap-2">
                              {item.key_concepts.map((concept, idx) => (
                                <span 
                                  key={idx}
                                  className={`text-xs px-2 py-1 rounded ${darkMode ? 'bg-purple-900/30 text-purple-300' : 'bg-purple-100 text-purple-700'}`}
                                >
                                  {concept}
                                </span>
                              ))}
                            </div>
                          </div>
                        )}

                        {/* Projects */}
                        {item.projects && item.projects.length > 0 && (
                          <div className="mt-3">
                            <p className={`text-sm font-medium mb-2 ${darkMode ? 'text-gray-300' : 'text-gray-700'}`}>
                              🚀 Build These Projects:
                            </p>
                            <ul className="space-y-1">
                              {item.projects.map((project, idx) => (
                                <li key={idx} className={`text-sm ${darkMode ? 'text-gray-300' : 'text-gray-600'}`}>
                                  • {project}
                                </li>
                              ))}
                            </ul>
                          </div>
                        )}
                      </div>
                    ))}
                  </div>

                  {levelIndex < 2 && (
                    <div className="flex justify-center my-6">
                      <div className={`text-4xl ${darkMode ? 'text-gray-600' : 'text-gray-400'}`}>↓</div>
                    </div>
                  )}
                </div>
              )
            ))}
          </div>

          {/* Footer CTA */}
          <div className={`mt-8 p-6 rounded-xl ${darkMode ? 'bg-gradient-to-r from-green-900/30 to-blue-900/30 border border-green-500' : 'bg-gradient-to-r from-green-50 to-blue-50 border border-green-200'} shadow-lg`}>
            <h4 className={`text-lg font-bold mb-2 ${darkMode ? 'text-white' : 'text-gray-900'}`}>
              🎉 Ready to Start Your Journey?
            </h4>
            <p className={`text-sm ${darkMode ? 'text-gray-300' : 'text-gray-700'}`}>
              This roadmap is personalized for you based on your current skills. Focus on one level at a time, and you'll be ready for your dream role as a {result.target_role}!
            </p>
          </div>
            </>
          )}
        </div>
      )}
    </div>
  );
};

export default Roadmap;
